import type { PassportData } from './passport-data';

/**
 * Pre-extracted reference passport data matching the user's provided
 * Tchibo FiTS Specification (Project 151546) & Bureau Veritas Test Report ((6825)298-0551).
 * Can be loaded as an instant sample in the AI PDF Auto-Fill dialog.
 */
export const EXTRACTED_TCHIBO_PASSPORT: PassportData = {
  general: {
    projectId: '151546',
    orderNo: '4300085070',
    version: '4 updated',
    completeness: 98,
    updatedDate: '30 Oct 2025',
    productName: "Men's Shorty Pyjamas, Modal",
    subtitle: 'Modal Single Jersey Sleepwear Set · Tchibo FiTS Certified',
    brand: 'Tchibo',
    season: 'SS26',
    category: 'Sleepwear & Lounge',
    status: 'VERIFIED',
    designDescription:
      'Short-sleeved V-neck top with self-fabric piping, 2 cm forward shoulder seam, paired with set-on waistband shorts featuring internal drawstring, side pockets, and bottom coverstitch.',
    weightGsm: 160,
    originCountry: 'Bangladesh',
    lifetimeYears: '4+ Years (Tested for 10+ wash/dry cycles)',
    carbonKg: 3.42,
    qrCodeSeed: 'https://tchibo.dpp.eu/p/151546-4300085070',
    qrCodeLab: 'BV-BD-(6825)298-0551-FITS',
    badges: ['Cotton made in Africa (CmiA)', 'OEKO-TEX Standard 100', 'Birla Livaeco Modal', 'BV Tested PASS'],
    articleNumbers: {
      uni: {
        S: '730801',
        M: '730798',
        L: '730802',
        XL: '730799',
        XXL: '730800',
      },
      aop: {
        S: '730793',
        M: '730794',
        L: '730796',
        XL: '730797',
        XXL: '730795',
      },
    },
    visuals: {
      cw1Name: 'Jadeite (Pantone 16-5304 TCX)',
      cw1Image: '',
      cw2Name: 'Dark Green (COLORO 097-36-06 / AOP 085-52-07)',
      cw2Image: '',
      aiModelInfo: 'Extracted via Gemini 3.8 Flash from Tchibo FiTS & Bureau Veritas Test Report',
      prompt: 'men shorty pyjamas modal single jersey Tchibo technical specification and test report',
      colors: 'Jadeite (Top/Bottom) · Dark Green (Top/Bottom) · AOP Geometric Hexagon Pattern',
    },
  },
  materials: {
    cotton: 48,
    modal: 47,
    elastane: 5,
    recycledContent: 0,
    fabricWeight: 160,
    tolerance: '±3% (ISO 1833 compliant)',
    yarnSources: {
      cottonCert: 'Cotton made in Africa (CmiA) certified spinning mill · Registered in SCOT tracking tool',
      modalCert: 'Nominated Modal: Birla Livaeco / Lenzing TENCEL™',
      elastaneCert: 'Nominated Elastane: creora® by Creora / LYCRA® / ROICA®',
    },
    labAnalysis: [
      { fiber: 'Cotton (CmiA)', labeled: '48.0%', lab: '49.3% (Avg A-D)' },
      { fiber: 'Modal (Birla)', labeled: '47.0%', lab: '46.8% (Avg A-D)' },
      { fiber: 'Elastane (creora®)', labeled: '5.0%', lab: '3.8% (Avg A-D)' },
    ],
    microfibreNote:
      'High-cellulosic composition (95% cotton + modal) substantially reduces synthetic microfiber shedding compared to standard polyester pyjamas.',
    svhcSubstances: [
      {
        substance: 'Extractable Heavy Metals (As, Cd, Pb, Hg, Cu, Cr, Co, Ni, Ba, Se)',
        cas: 'DIN EN 16711-2',
        component: 'Shell & Contrast Fabric',
        status: 'PASS (All ND)',
      },
      {
        substance: 'Azo Amines & Arylamine Salts (Splitting off Amines)',
        cas: 'EN ISO 14362-1:2017',
        component: 'Dyed Jersey & Threads',
        status: 'PASS (ND <5 mg/kg)',
      },
      {
        substance: 'Phthalates (DINP, DNOP, DEHP, DIDP, BBP, DBP, DIBP)',
        cas: 'EN ISO 14389',
        component: 'Elastic tape & prints',
        status: 'PASS (ND <50 mg/kg)',
      },
      {
        substance: 'Formaldehyde',
        cas: 'DIN EN ISO 14184-1',
        component: 'Shell & pocket bags',
        status: 'PASS (ND <16 mg/kg)',
      },
      {
        substance: 'Cyclic Siloxanes (D4, D5, D6)',
        cas: '556-67-2 / 541-02-6',
        component: 'Softener & finishing',
        status: 'PASS (ND <500 mg/kg)',
      },
      {
        substance: 'Chlorinated Paraffins (SCCP & MCCP)',
        cas: 'ISO 22818',
        component: 'Elastic & mobilon tape',
        status: 'PASS (ND <50 mg/kg)',
      },
    ],
  },
  measurements: {
    categoryType: 'two_piece',
    sizeHeaders: ['S', 'M', 'L', 'XL', 'XXL'],
    allowedShrinkage: 'Allowed dimensional change after wash: -6.0% / +1.0%',
    pomCount: 16,
    topFit:
      'V-neck single jersey top with self-fabric piping, overlap topstitch, continuous back necktape, forward shoulder seam (approx 2cm), and 3-thread bottom coverstitch at 2.5cm.',
    bottomFit:
      'Straight leg short with set-on waistband, 3.5cm elastic & drawstring tunnel inside, side pocket bartacks at 0.6cm width, and 3-thread coverstitch hem.',
    onePieceFit: 'n/a',
    top: [
      { k: 'C', name: '1/2 Chest (2cm below armhole)', how: 'Measured straight 2cm below armhole', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 50, M: 54, L: 58, XL: 62, XXL: 66 }, g: 'Chest' },
      { k: 'B', name: '1/2 Bottom Hem', how: 'Measured straight along bottom hem', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 49, M: 53, L: 57, XL: 61, XXL: 65 }, g: 'Hem' },
      { k: 'STS', name: 'Shoulder to Shoulder', how: 'Distance between outer shoulder points', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 46, M: 48, L: 50, XL: 52, XXL: 54 }, g: 'Shoulders' },
      { k: 'BL', name: 'Back Length', how: 'From highest shoulder point (HSP)', tolMinus: -1.5, tolPlus: 1.5, vals: { S: 73, M: 75, L: 77, XL: 79, XXL: 81 }, g: 'Length' },
      { k: 'SL', name: 'Sleeve Length', how: 'Along sleeve-fold', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 21, M: 22, L: 23, XL: 24, XXL: 25 }, g: 'Sleeve' },
      { k: 'AS', name: 'Armhole Straight', how: 'Measured at right angle', tolMinus: -0.5, tolPlus: 0.5, vals: { S: 23, M: 24, L: 25, XL: 26, XXL: 27 }, g: 'Armhole' },
      { k: 'NO', name: 'Neck Opening', how: 'Measured straight seam to seam', tolMinus: -0.5, tolPlus: 0.5, vals: { S: 17.5, M: 18, L: 18.5, XL: 19, XXL: 19.5 }, g: 'Neck' },
      { k: 'NDF', name: 'Neck Drop Front', how: 'From HSP to front neckline', tolMinus: -0.5, tolPlus: 0.5, vals: { S: 16, M: 16.5, L: 17, XL: 17.5, XXL: 18 }, g: 'Neck' },
    ],
    bottom: [
      { k: 'WB', name: '1/2 Waistband Relaxed', how: 'Measured straight along edge', tolMinus: -1.5, tolPlus: 1.5, vals: { S: 36, M: 39, L: 42, XL: 45, XXL: 48 }, g: 'Waist' },
      { k: 'WBS', name: '1/2 Waistband Stretched', how: 'Minimum stretchability', tolMinus: -2.0, tolPlus: 2.0, vals: { S: 47, M: 50, L: 53, XL: 56, XXL: 59 }, g: 'Waist' },
      { k: 'H', name: '1/2 Hip', how: 'Measured straight at hip height', tolMinus: -1.5, tolPlus: 1.5, vals: { S: 51, M: 54, L: 57, XL: 60, XXL: 63 }, g: 'Hip' },
      { k: 'IL', name: 'Inseam Length', how: 'Along inseam', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 14, M: 15, L: 16, XL: 17, XXL: 18 }, g: 'Inseam' },
      { k: 'T', name: '1/2 Thigh', how: 'From fold to fold (per sketch)', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 32, M: 34, L: 36, XL: 38, XXL: 40 }, g: 'Thigh' },
      { k: 'FR', name: 'Front Rise', how: 'Along seam including waistband', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 29, M: 30, L: 31, XL: 32, XXL: 33 }, g: 'Rise' },
      { k: 'BR', name: 'Back Rise', how: 'Along seam including waistband', tolMinus: -1.0, tolPlus: 1.0, vals: { S: 41.5, M: 42.5, L: 43.5, XL: 44.5, XXL: 45.5 }, g: 'Rise' },
      { k: 'CL', name: 'Drawcord Total Length', how: 'Visible length / total length', tolMinus: -5.0, tolPlus: 5.0, vals: { S: 140, M: 150, L: 160, XL: 170, XXL: 180 }, g: 'Drawcord' },
    ],
    onePiece: [],
  },
  traceability: {
    percentage: 100,
    summary:
      'Complete Tier 1 to Tier 4 verified supply chain audit through SCOT (Sustainable Cotton Tracker) and Bureau Veritas Bangladesh inspection.',
    nodes: [
      {
        tier: 'Tier 1 — Garment Cut & Sew',
        date: 'Oct 2025',
        title: 'AKH Knitting & Dyeing Ltd.',
        subtitle: 'Plot # 130, DEPZ Extension Area, Ganakbari, Savar, Dhaka, Bangladesh',
        color: 'green',
        items: [
          { label: 'Facility', val: 'AKH Savar Unit 4' },
          { label: 'Certifications', val: 'Amfori BSCI Grade A · Accord / RSC Compliant' },
          { label: 'Auditor', val: 'Bureau Veritas Consumer Products (BD) Ltd.' },
          { label: 'Labour Standard', val: 'Fair wage, healthcare & free transport' },
        ],
      },
      {
        tier: 'Tier 2 — Fabric Knitting & Dyeing',
        date: 'Sep 2025',
        title: 'AKH Dyeing & Finishing Division',
        subtitle: 'Savar Industrial Area, Dhaka, Bangladesh',
        color: 'green',
        items: [
          { label: 'Process', val: 'Single jersey circular knitting (32x28 gauge)' },
          { label: 'Dyeing', val: 'Low-liquor reactive dye, Oeko-Tex Eco-Passport' },
          { label: 'Effluent Treatment', val: 'Biological ETP with 85% water recycling' },
          { label: 'Finishing', val: 'Mechanical compaction & eco-softener' },
        ],
      },
      {
        tier: 'Tier 3 — Yarn Spinning',
        date: 'Aug 2025',
        title: 'CmiA Registered Spinning Mills / Birla Cellulose',
        subtitle: 'Kharach & Bharuch Facilities (India) & SCOT Network',
        color: 'green',
        items: [
          { label: 'Yarn Construction', val: 'Ring spun combed Ne 34/1, 20 D (S-twist)' },
          { label: 'Modal Source', val: 'Birla Livaeco / FSC certified pulp' },
          { label: 'Tracking Tool', val: 'CmiA SCOT Account verified' },
          { label: 'Elastane', val: 'creora® spandex by Hyosung' },
        ],
      },
      {
        tier: 'Tier 4 — Raw Material Farming',
        date: 'Jun 2025',
        title: 'Cotton made in Africa (CmiA) Smallholders',
        subtitle: 'Sub-Saharan Africa CmiA Certified Farm Cooperatives',
        color: 'green',
        items: [
          { label: 'Agriculture', val: '100% Rainfed cotton (zero artificial irrigation)' },
          { label: 'GMO Policy', val: 'Strict zero genetically modified organisms (non-GMO)' },
          { label: 'Smallholder Income', val: 'Fair pricing & agricultural training' },
          { label: 'Cellulose Origin', val: 'FSC/PEFC sustainably managed wood plantations' },
        ],
      },
    ],
  },
  quality: {
    rslStandards: 'Tchibo RSL Category 1 (v1/2024), FiTS dated 13 Aug 2025 & EU REACH Annex XVII',
    rslItems: [
      { name: 'Formaldehyde (DIN EN ISO 14184-1)', result: 'PASS — ND (<16 mg/kg) vs limit 75' },
      { name: 'pH Value (EN ISO 3071)', result: 'PASS — 5.5 to 6.5 vs limit 4.0–7.5' },
      { name: 'Extractable Heavy Metals (DIN EN 16711-2)', result: 'PASS — All metals (As, Cd, Pb, Hg, Cu, Cr, Ni, Ba, Se) ND' },
      { name: 'Azo Colorants & Amines (EN ISO 14362-1)', result: 'PASS — ND (<5 mg/kg) vs limit 20' },
      { name: 'Phthalates (EN ISO 14389)', result: 'PASS — ND (<50 mg/kg) vs limit 1000 sum' },
      { name: 'Cyclic Siloxanes (D4, D5, D6)', result: 'PASS — ND (<500 mg/kg) vs limit 1000' },
      { name: 'Chlorinated Paraffins (SCCP / MCCP)', result: 'PASS — ND (<50 mg/kg) vs limit 1000' },
      { name: 'Odour Test (SNV 195651)', result: 'PASS — Grade 1 (No abnormal odour) vs limit Grade 3' },
    ],
    labCards: [
      {
        std: 'DIN EN ISO 105 C06',
        title: 'Colour Fastness to Washing',
        val: 'Grade 4–5',
        subVal: 'Colour Change & Staining (PASS)',
        desc: 'Hand wash at 40°C in 0.4% ECE reference detergent with 10 steel balls. Zero color fading on body & contrast.',
        hint: 'Exceeds Tchibo requirement of Grade 4',
      },
      {
        std: 'DIN EN ISO 105 E01',
        title: 'Colour Fastness to Water',
        val: 'Grade 4–5',
        subVal: 'Water Immersion (PASS)',
        desc: 'Tested against acetate, cotton, nylon, polyester, acrylic, and wool multifixture strips.',
        hint: 'Highest performance bracket',
      },
      {
        std: 'DIN EN ISO 105 X12',
        title: 'Colour Fastness to Rubbing',
        val: 'Dry 4–5 / Wet 4–5',
        subVal: 'Dry & Wet Crockmeter (PASS)',
        desc: 'Both lengthwise and widthwise rubbing cycles resulted in minimal to no dye transfer.',
        hint: 'Exceeds requirement of Grade 4',
      },
      {
        std: 'DIN EN ISO 105 B02',
        title: 'Colour Fastness to Light',
        val: 'Grade 4',
        subVal: 'Xenon Arc Lamp (PASS)',
        desc: 'Evaluated under simulated sunlight conditions; colors retain original vibrancy without fading.',
        hint: 'Complies with European retail standards',
      },
      {
        std: 'DIN EN ISO 105-E04',
        title: 'Colour Fastness to Perspiration',
        val: 'Grade 4–5',
        subVal: 'Acidic & Alkaline Perspiration (PASS)',
        desc: 'Tested in both synthetic acid and alkaline sweat solutions without staining adjacent fibers.',
        hint: 'Optimal comfort for sleepwear garments',
      },
      {
        std: 'ISO 1833',
        title: 'Quantitative Fibre Composition',
        val: '48/47/5 Blend',
        subVal: 'Cotton 49.3% · Modal 46.8% · Elastane 3.8%',
        desc: 'Fibre tolerance is well within statutory ±3% European regulations (EU Regulation No. 1007/2011).',
        hint: 'Perfect match with customer label declaration',
      },
    ],
  },
  care: {
    wash: '40°C machine wash with gentle cycle',
    bleach: 'Do not bleach (oxygen or chlorine)',
    dry: 'Do not tumble dry (line dry in shade)',
    iron: 'Iron low heat (max 110°C, iron inside out)',
    dryClean: 'Do not dry clean',
    labelWording:
      'Wir empfehlen Colorwaschmittel / Colour detergent recommended / Mit ähnlichen Farben waschen / Wash with similar colours / Laver avec des couleurs similaires / Renkli çamaşır deterjanı kullanmanızı tavsiye ederiz / Prát s podobnými barvami.',
  },
  circularity: {
    tips: [
      {
        emoji: '💧',
        title: 'Wash Cool & Full',
        text: 'Washing at 30°C or 40°C with similar dark colours preserves modal softness and conserves up to 45% electricity per wash cycle.',
      },
      {
        emoji: '🌬️',
        title: 'Air Dry Flat',
        text: 'Line drying modal jersey prevents elastane heat-breakdown, eliminating unwanted shrinkage and keeping shape for years.',
      },
      {
        emoji: '🪡',
        title: 'Simple Seam Repair',
        text: 'The 4-thread overlock seams and waistband drawstring tunnel can be easily re-threaded with standard cotton thread if needed.',
      },
    ],
    upcycleTitle: 'Sleepwear to Soft Loungewear or Reusable Sleep Mask',
    upcycleSubtitle: 'Modal single jersey is exceptionally soft on sensitive skin',
    upcycleImage: '',
    upcycleSteps: [
      {
        title: 'Step 1: Reusable Travel Pouch',
        text: 'Cut a 20x25cm panel from the shorts body. Fold and sew three sides, utilizing the original drawstring as a cinch cord.',
      },
      {
        title: 'Step 2: Gentle Hair Scrunchies',
        text: 'Cut remaining jersey into 8x30cm strips. Thread elastic band through and sew ends for snag-free sleep scrunchies.',
      },
      {
        title: 'Step 3: Textile-to-Textile Mechanical Recycling',
        text: 'When worn beyond repair, drop off at any Tchibo textile takeback bin for closed-loop cellulosic fiber regeneration.',
      },
    ],
    fibreRecyclingFacts: [
      '95% natural cellulosic composition (cotton + modal) allows high-yield mechanical and chemical recycling into new viscose or lyocell pulp.',
      'Elastane content is restricted to <5% to ensure full compatibility with emerging circular sorting and shredding facilities.',
    ],
  },
  environmental: {
    totalCarbon: 3.42,
    carbonBreakdown: [
      { label: 'CmiA Cotton & Wood Pulp', value: 38, color: '#2E6B4F' },
      { label: 'Knitting, Dyeing & Finishing', value: 29, color: '#4A9B71' },
      { label: 'Garment Assembly (AKH)', value: 16, color: '#8CB89F' },
      { label: 'Sea Freight & Logistics', value: 11, color: '#C49A45' },
      { label: 'Retail & Consumer Use', value: 6, color: '#8C827A' },
    ],
    waterUsage: {
      value: 165,
      max: 1200,
      sub: 'CmiA cotton requires zero artificial irrigation; dyeing operates on low-liquor ratio machinery',
    },
    renewableEnergy: {
      value: 74,
      max: 100,
      sub: 'Facility powered by on-site rooftop solar and biomass-assisted co-generation',
    },
    recycledPackaging: {
      value: 92,
      max: 100,
      sub: 'GOTS compliant packaging; 100% post-consumer recycled polybag and FSC kraft hangtags',
    },
    packagingRecyclability: 98,
    packagingMaterials: 'Single-polymer LDPE polybag (#4) with water-based non-toxic inks + FSC paper hangtag',
    euPolicyNote: 'Fully conforms with EU Ecodesign for Sustainable Products Regulation (ESPR) and Corporate Sustainability Due Diligence Directive (CSDDD).',
  },
  compliance: {
    certifications: [
      { name: 'Cotton made in Africa (CmiA)', scope: 'Sustainable agricultural practices & farmer welfare', status: 'Certified & SCOT Verified' },
      { name: 'Bureau Veritas Lab Inspection', scope: 'Harmful substances & physical durability (Report (6825)298-0551)', status: 'Full PASS' },
      { name: 'EU REACH Regulation (EC 1907/2006)', scope: 'SVHC declaration: <0.1% for all components & packaging', status: 'Compliant' },
      { name: 'Tchibo FiTS RSL Category 1', scope: 'Restricted Substances List v1/2024 compliance', status: 'Approved' },
    ],
    salesChannel: 'Tchibo E-Commerce & Retail Stores',
    availableFrom: 'Spring / Summer 2026',
    usageClass: 'Apparel Class II (Direct Skin Contact)',
    afterSale: 'Tchibo 30-Day Free Return & Customer Guarantee',
    issuer: 'Tchibo GmbH · Hamburg, Germany',
    markets: 'Germany, Austria, Czech Republic, Poland, Slovakia, Hungary, Switzerland, Turkey',
  },
};

/**
 * Pre-extracted reference passport data for a One-Piece Garment (Baby Sleepsuit / Romper)
 * Demonstrating categoryType: 'one_piece', dynamic sizing (50/56 - 98/104), tolerances,
 * and strict 'n/a' for missing values.
 */
export const EXTRACTED_BABY_SLEEPSUIT_PASSPORT: PassportData = {
  general: {
    projectId: '152890',
    orderNo: '4300086110',
    version: '2 updated',
    completeness: 97,
    updatedDate: '12 Nov 2025',
    productName: "Baby's Long-Sleeve Romper Sleepsuit, Organic Cotton",
    subtitle: '100% Organic Cotton Interlock · Two-Way Safety Zipper · Tchibo FiTS Certified',
    brand: 'Tchibo',
    season: 'AW25',
    category: 'Babywear & Sleepwear',
    gender: 'Baby / Unisex',
    color: 'Oatmeal Melange / Forest Animals Print',
    fitting: 'Comfort Baby Fit',
    passportId: 'DPP-152890-4300086110',
    status: 'VERIFIED',
    designDescription:
      'Long-sleeve one-piece sleepsuit with full-length two-way safety zipper, protective chin guard, foldable scratch mittens on sleeves, soft rib neckband, and gusseted crotch construction.',
    weightGsm: 200,
    originCountry: 'India',
    lifetimeYears: '3+ Years (Engineered for multiple sibling hand-me-downs)',
    carbonKg: 2.15,
    qrCodeSeed: 'https://tchibo.dpp.eu/p/152890-4300086110',
    qrCodeLab: 'SGS-IN-GRT250912-FITS',
    badges: ['GOTS Certified Organic', 'OEKO-TEX Standard 100 Class 1 (Baby)', 'Nickel-Free Hardware', 'Safe Zip Guard'],
    articleNumbers: {
      uni: {
        '50/56': '741201',
        '62/68': '741202',
        '74/80': '741203',
        '86/92': '741204',
        '98/104': '741205',
      },
      aop: {
        '50/56': '741211',
        '62/68': '741212',
        '74/80': '741213',
        '86/92': '741214',
        '98/104': '741215',
      },
    },
    gtinStatus: 'VERIFIED',
    gtinCodes: {
      uni: {
        '50/56': '4061234741201',
        '62/68': '4061234741202',
        '74/80': '4061234741203',
        '86/92': '4061234741204',
        '98/104': '4061234741205',
      },
      aop: {
        '50/56': '4061234741211',
        '62/68': '4061234741212',
        '74/80': '4061234741213',
        '86/92': '4061234741214',
        '98/104': '4061234741215',
      },
    },
    packagingInfo: {
      materials: '100% Recycled LDPE polybag + FSC certified hangtag',
      recyclability: '99%',
      type: 'Flat-pack baby apparel fold',
      certification: 'FSC® Mix (CU-COC-812034)',
    },
    visuals: {
      cw1Name: 'Oatmeal Melange (Pantone 13-0401 TCX)',
      cw1Image: '',
      cw2Name: 'Forest Animals Print (Coloro 054-68-18)',
      cw2Image: '',
      aiModelInfo: 'Extracted via Gemini 3.8 Flash from Technical Specification & SGS Lab Report',
      prompt: 'baby organic cotton zip romper sleepsuit technical drawing and measurement pack',
      colors: 'Oatmeal Solid · Forest Green Print · Natural Ivory Trims',
      gallery: [
        { id: 'cw-1', name: 'CW 01', colorName: 'Oatmeal Melange', pantone: '13-0401 TCX', url: '', side: 'Front View' },
        { id: 'cw-2', name: 'CW 02', colorName: 'Forest Animals Print', pantone: '16-5808 TCX', url: '', side: 'All-Over Print' },
      ],
    },
  },
  materials: {
    cotton: 100,
    modal: 0,
    elastane: 0,
    viscose: 0,
    recycledContent: 0,
    fabricWeight: 200,
    tolerance: '±3% (ISO 1833 compliant)',
    yarnSources: {
      cottonCert: 'GOTS Certified Organic Cotton (License CU 851940) · Combed ring spun Ne 40/1 interlock',
      modalCert: 'n/a',
      viscoseCert: 'n/a',
      elastaneCert: 'n/a',
    },
    labAnalysis: [
      { fiber: 'Organic Cotton', labeled: '100.0%', lab: '100.0% (Single Component)' },
    ],
    microfibreNote: '100% natural organic cotton cellulosic fibers; zero synthetic microfiber shed.',
    svhcSubstances: [
      { substance: 'Extractable Heavy Metals (As, Cd, Pb, Hg, Cu, Cr, Co, Ni)', cas: 'DIN EN 16711-2', component: 'Fabric & Metal Snaps', status: 'PASS (All ND)' },
      { substance: 'Azo Colorants & Cleavable Arylamines', cas: 'EN ISO 14362-1:2017', component: 'Dyed Interlock & Rib', status: 'PASS (ND <5 mg/kg)' },
      { substance: 'Phthalates (Total 14 congeners)', cas: 'EN ISO 14389', component: 'Zipper tape & prints', status: 'PASS (ND <20 mg/kg)' },
      { substance: 'Formaldehyde (ISO 14184-1)', cas: 'DIN EN ISO 14184-1', component: 'Shell & Interlock', status: 'PASS (ND <10 mg/kg)' },
      { substance: 'Allergenic Disperse Dyes', cas: 'DIN 54231', component: 'Print & Dyeing', status: 'PASS (ND)' },
    ],
  },
  measurements: {
    categoryType: 'one_piece',
    sizeHeaders: ['50/56', '62/68', '74/80', '86/92', '98/104'],
    allowedShrinkage: 'Allowed dimensional change after wash: length -5.0% / width -4.0%',
    pomCount: 8,
    topFit: 'n/a',
    bottomFit: 'n/a',
    onePieceFit: 'One-piece sleepsuit with continuous two-way safety zipper, chin protection tab, raglan sleeves, and stretch rib cuffs.',
    top: [],
    bottom: [],
    onePiece: [
      { k: '1', name: 'Total Length (HSP to Crotch)', how: 'From highest shoulder point to inside crotch seam', tolMinus: -1.0, tolPlus: 1.0, vals: { '50/56': 36, '62/68': 40, '74/80': 44, '86/92': 48, '98/104': 52 }, g: 'Length' },
      { k: '2', name: 'Total Full Length (HSP to Leg Hem)', how: 'From highest shoulder point down to bottom leg hem', tolMinus: -1.5, tolPlus: 1.5, vals: { '50/56': 50, '62/68': 58, '74/80': 66, '86/92': 74, '98/104': 82 }, g: 'Length' },
      { k: '3', name: '1/2 Chest (2cm below armhole)', how: 'Measured straight across 2cm below armpit fold', tolMinus: -1.0, tolPlus: 1.0, vals: { '50/56': 23, '62/68': 25, '74/80': 27, '86/92': 29, '98/104': 31 }, g: 'Chest' },
      { k: '4', name: '1/2 Hip Width', how: 'Measured straight across widest hip level', tolMinus: -1.0, tolPlus: 1.0, vals: { '50/56': 25, '62/68': 27, '74/80': 29, '86/92': 31, '98/104': 33 }, g: 'Hip' },
      { k: '5', name: 'Sleeve Length Raglan (from Neck)', how: 'From neck seam along outer curve to sleeve edge', tolMinus: -1.0, tolPlus: 1.0, vals: { '50/56': 24, '62/68': 28, '74/80': 32, '86/92': 36, '98/104': 40 }, g: 'Sleeve' },
      { k: '6', name: 'Inseam Length', how: 'From crotch point along inseam to leg hem', tolMinus: -1.0, tolPlus: 1.0, vals: { '50/56': 16, '62/68': 20, '74/80': 24, '86/92': 28, '98/104': 32 }, g: 'Inseam' },
      { k: '7', name: '1/2 Leg Opening / Hem', how: 'Measured straight along ribbed ankle cuff', tolMinus: -0.5, tolPlus: 0.5, vals: { '50/56': 6.5, '62/68': 7.0, '74/80': 7.5, '86/92': 8.0, '98/104': 8.5 }, g: 'Hem' },
      { k: '8', name: 'Neck Opening Width', how: 'Straight across neck rib relaxed', tolMinus: -0.5, tolPlus: 0.5, vals: { '50/56': 11.5, '62/68': 12.0, '74/80': 12.5, '86/92': 13.0, '98/104': 13.5 }, g: 'Neck' },
    ],
  },
  traceability: {
    percentage: 100,
    summary: 'Direct farm-to-garment certified supply chain audited through GOTS Certificate of Compliance CU851940 and SGS India inspection.',
    origin: {
      country: 'India',
      city: 'Tirupur, Tamil Nadu',
      facility: 'Armstrong Knitting Mills Ltd.',
      lat: 11.1085,
      lng: 77.3411,
    },
    destination: {
      country: 'Germany',
      city: 'Hamburg',
      label: 'Hamburg Central Logistics Hub, Germany',
      lat: 53.5511,
      lng: 9.9937,
      transportMode: 'Maritime Container Sea Freight (Nhava Sheva ➔ Hamburg)',
      distanceKm: 12800,
    },
    testingLab: {
      name: 'SGS India Pvt. Ltd. Consumer Testing Services',
      reportNo: 'GRT-250912-0041',
      location: 'Tirupur, Tamil Nadu, India',
      result: 'PASS',
    },
    nodes: [
      {
        tier: 'Tier 1 — Cut, Make & Trim (CMT)',
        date: 'Oct 2025',
        title: 'Armstrong Knitting Mills (Unit 2)',
        subtitle: 'Tirupur, Tamil Nadu, India · GOTS Organic Certified Facility',
        color: 'green',
        items: [
          { label: 'Facility', val: 'Armstrong Unit 2 (Babywear Spec)' },
          { label: 'Certifications', val: 'GOTS CU 851940 · SA8000 · ISO 9001' },
          { label: 'Auditor', val: 'SGS Consumer Testing Services' },
        ],
      },
      {
        tier: 'Tier 2 — Knitting & Eco-Dyeing',
        date: 'Sep 2025',
        title: 'Armstrong Eco-Dyeing & Finishing Division',
        subtitle: 'Perundurai SIPCOT, Tamil Nadu, India · Zero Liquid Discharge (ZLD)',
        color: 'green',
        items: [
          { label: 'Fabrication', val: 'Interlock 200 g/m² combed organic cotton' },
          { label: 'Water Treatment', val: '100% Zero Liquid Discharge (ZLD) RO plant' },
          { label: 'Dyes', val: 'GOTS approved low-impact bio-reactive dyes' },
        ],
      },
      {
        tier: 'Tier 3 — Ginning & Spinning',
        date: 'Aug 2025',
        title: 'Vardhman Organic Spinners',
        subtitle: 'Madhya Pradesh & Gujarat, India',
        color: 'green',
        items: [
          { label: 'Yarn Count', val: 'Combed ring spun Ne 40/1' },
          { label: 'Standard', val: '100% GOTS certified organic staple cotton' },
        ],
      },
      {
        tier: 'Tier 4 — Organic Farming Cooperative',
        date: 'Jun 2025',
        title: 'Chetna Organic Farmers Association',
        subtitle: 'Maharashtra & Odisha, India',
        color: 'green',
        items: [
          { label: 'Agriculture', val: 'Non-GMO, rain-fed bio-organic cultivation' },
          { label: 'Fair Trade', val: 'Fairtrade Premium paid to farming families' },
        ],
      },
    ],
  },
  quality: {
    rslStandards: 'Tchibo RSL Category 1 (Babywear Class 1) & OEKO-TEX Standard 100 Class 1',
    reportNumber: 'GRT-250912-0041',
    overallResult: 'PASS',
    testingLab: 'SGS India Pvt. Ltd. Consumer Testing Services',
    universalFastnessKey: 'Universal Fastness Rating: Grade 5 = Excellent (No Change) · Grade 4 = Good · Grade 3 = Moderate · Grade 2 = Poor · Grade 1 = Very Poor',
    reviewedBy: {
      name: 'Dr. K. Senthil Kumar',
      designation: 'Head of Quality & Safety – Textile Testing Division',
      date: '15 Nov 2025',
    },
    rslItems: [
      { name: 'Formaldehyde (DIN EN ISO 14184-1)', result: 'PASS — ND (<10 mg/kg) vs baby limit 16' },
      { name: 'pH Value (EN ISO 3071)', result: 'PASS — 6.2 vs baby range 4.0–7.5' },
      { name: 'Extractable Heavy Metals (DIN EN 16711-2)', result: 'PASS — All metals ND vs Class 1 limits' },
      { name: 'Azo Amines (EN ISO 14362-1)', result: 'PASS — ND (<5 mg/kg) vs limit 20' },
      { name: 'Phthalates (EN ISO 14389)', result: 'PASS — ND (<20 mg/kg) vs baby limit 500' },
      { name: 'Saliva & Perspiration Fastness (DIN 53160-1/2)', result: 'PASS — Grade 5 (Zero bleeding)' },
      { name: 'Nickel Release on Snaps (EN 1811)', result: 'PASS — <0.1 µg/cm²/week (Pass nickel-free)' },
      { name: 'Odour Test (SNV 195651)', result: 'PASS — Grade 1 (Odorless)' },
    ],
    labCards: [
      {
        std: 'DIN 53160-1 / 2',
        title: 'Fastness to Saliva & Perspiration',
        val: 'Grade 5',
        subVal: 'Zero bleeding (PASS)',
        desc: 'Tested under synthetic saliva and acid perspiration solutions with filter swatches. Completely safe for infants mouthing garment fabric.',
        hint: 'German LFGB §64 & EU Toy Safety directive compliant',
      },
      {
        std: 'BS 7907 / EN 71-1',
        title: 'Small Parts & Fastener Security',
        val: '>90 N (PASS)',
        subVal: 'Tensile pull test 90N / 10s',
        desc: 'Zipper puller, slider stops, and snap buttons tested to withstand >90 Newtons of tensile force with zero detachment.',
        hint: 'Exceeds European infant choking prevention standard',
      },
      {
        std: 'DIN EN ISO 105 C06',
        title: 'Colour Fastness to 60°C Washing',
        val: 'Grade 4–5',
        subVal: 'High-temperature hygiene wash (PASS)',
        desc: 'Tested at 60°C in ECE detergent with sodium perborate. Outstanding color retention on pastel dyes.',
        hint: 'Hospital-grade sanitization wash verified',
      },
      {
        std: 'DIN EN ISO 105 X12',
        title: 'Colour Fastness to Rubbing',
        val: 'Dry 4–5 / Wet 4–5',
        subVal: 'Dry & Wet Crockmeter (PASS)',
        desc: 'Zero dye transfer detected during dry and wet rubbing friction cycles.',
        hint: 'Exceeds requirement of Grade 4',
      },
      {
        std: 'DIN EN 16732',
        title: 'Zipper Mechanical Endurance',
        val: 'PASS (500 cycles)',
        subVal: 'Two-way nylon coil zipper',
        desc: 'Smooth operation across 500 opening and closing cycles without chain separation or zipper slider jam.',
        hint: 'Baby-safe enclosed zipper teeth',
      },
    ],
  },
  care: {
    wash: '60°C machine wash with gentle cycle',
    bleach: 'Do not bleach (oxygen or chlorine)',
    dry: 'Tumble dry low heat',
    iron: 'Iron medium heat (max 150°C)',
    dryClean: 'Do not dry clean',
    labelWording:
      '60°C Schonwäsche / 60°C gentle wash / Mit ähnlichen Farben waschen / Wash with similar colours / Vor dem Waschen Reißverschluss schließen / Close zipper before washing.',
    stainRemovalHacks: {
      oilAndGrease: 'Pre-treat baby cream or baby oil with mild fragrance-free dish soap, let sit for 10 minutes, then wash at 60°C.',
      ink: 'n/a',
      foodAndDrinks: 'Rinse milk, formula, or vegetable purée immediately under cold water. Soak in warm water with oxygen bleach booster before washing.',
    },
  },
  circularity: {
    tips: [
      { emoji: '👶', title: 'Pass to Sibling or Friend', text: 'Reinforced interlock cotton retains softness through 50+ wash cycles, making it ideal for second-life baby use.' },
      { emoji: '🧼', title: 'Wash at 40°C for Everyday', text: 'Wash at 40°C for standard days and 60°C only when deep sanitization is needed to save up to 40% electricity.' },
      { emoji: '♻️', title: 'Closed-Loop Recycling', text: 'Pure mono-material 100% cotton structure allows seamless textile-to-textile recycling at end of life.' },
    ],
    upcycleTitle: 'Baby Sleepsuit to Soft Sensory Teething Cloth or Drool Bibs',
    upcycleSubtitle: '100% GOTS certified organic interlock is ultra-gentle on delicate infant skin',
    upcycleImage: '',
    upcycleSteps: [
      { title: 'Step 1: Double-Layer Triangle Bibs', text: 'Cut 25x25cm triangles from the body panels. Stitch edges together and add a snap closure for an absorbent organic bib.' },
      { title: 'Step 2: Washable Facial Wipes', text: 'Cut sleeves into 10x10cm squares, finish edges with a zigzag stitch, and use as reusable chemical-free baby wipes.' },
      { title: 'Step 3: Textile Regeneration', text: 'Remove the nylon zipper and drop off at Tchibo in-store textile take-back bins for cellulosic regeneration.' },
    ],
    fibreRecyclingFacts: [
      '100% mono-material organic cotton facilitates unhindered mechanical garnetting and chemical cellulosic dissolution into new staple fibers.',
      'Completely free of blended synthetic fibers or coatings, achieving 100% recyclability yield.',
    ],
  },
  environmental: {
    totalCarbon: 2.15,
    carbonBreakdown: [
      { label: 'Organic Cotton Cultivation', value: 32, color: '#2E6B4F' },
      { label: 'Spinning, Knitting & Eco-Dyeing', value: 34, color: '#4A9B71' },
      { label: 'Assembly & Finishing', value: 15, color: '#8CB89F' },
      { label: 'Logistics (Sea Freight)', value: 12, color: '#C49A45' },
      { label: 'Packaging & Distribution', value: 7, color: '#8C827A' },
    ],
    waterUsage: {
      value: 95,
      max: 1000,
      sub: 'Zero Liquid Discharge (ZLD) recycling 98% of processing water; rainfed organic cotton',
    },
    renewableEnergy: {
      value: 82,
      max: 100,
      sub: 'Solar photovoltaic rooftop array and state wind power wheeling grid',
    },
    recycledPackaging: {
      value: 100,
      max: 100,
      sub: '100% post-consumer recycled LDPE film and FSC certified paper',
    },
    packagingRecyclability: 100,
    packagingMaterials: 'GOTS compliant 100% recycled LDPE polybag + FSC certified unbleached kraft hangtag',
    euPolicyNote: 'Strictly satisfies EU Toy Safety, ESPR ecodesign rules, and OEKO-TEX Baby Class 1 specifications.',
  },
  compliance: {
    certifications: [
      { name: 'GOTS (Global Organic Textile Standard)', scope: 'Certified Organic Cotton Interlock (CU 851940)', status: 'Active & Verified' },
      { name: 'OEKO-TEX® Standard 100 Class 1 (Baby)', scope: 'Harmful substances compliance for infants 0-36 months', status: 'Certified PASS' },
      { name: 'SGS Lab Inspection Report', scope: 'Toxicological & physical small-parts durability (GRT-250912-0041)', status: 'Full PASS' },
      { name: 'EU REACH Regulation (EC 1907/2006)', scope: 'SVHC declaration: zero detection of all restricted candidate substances', status: 'Compliant' },
      { name: 'Tchibo FiTS RSL Category 1 (Baby)', scope: 'Strictest brand limits for children and infants', status: 'Approved' },
    ],
    salesChannel: 'Tchibo E-Commerce & Retail Branches',
    availableFrom: 'Autumn / Winter 2025',
    usageClass: 'Baby Apparel Class 1 (Direct infant contact)',
    afterSale: 'Tchibo 30-Day Free Return & Quality Guarantee',
    issuer: 'Tchibo GmbH · Überseering 18, 22297 Hamburg, Germany',
    markets: 'Germany, Austria, Switzerland, Poland, Czech Republic, Slovakia, Hungary',
  },
};
